### ISSUE TITLE
Intermittent StartIpc errors

### ISSUE THREAD

**Issue by dceddia** [timfish/sentry-rust-minidump#2]
I'm using this crate as part of sentry-tauri and it's going great, for the most part! I'm seeing errors reported from Rust and JS and it's been helpful to track things down.

I'm seeing a lot of reports of `StartIpc` errors of various flavors, though. Over the course of a week:

**StartIpc: No such file or directory (os error 2)**
Most frequent, only on Macs

**StartIpc: No connection could be made because the target machine actively refused it. (os error 10061)**
only on Windows

**StartIpc: An attempt was made to access a socket in a way forbidden by its access permissions. (os error 10013)**
just a handful, only on Windows

**StartIpc: An address incompatible with the requested protocol was used. (os error 10047)**
one occurrence, Windows

I've seen the `10061` error myself a few times, but it's pretty inconsistent. Looking at the code [here](https://github.com/timfish/sentry-rust-minidump/blob/master/src/client.rs#L42) I wonder if a timeout is causing that one.

The other ones I'm more confused by. I think most of them aren't seen by the user, but I wonder about `No such file or directory` and whether that means the app is failing to launch.

Let me know if there's any other info I can provide.

**Comment by timfish** [comment]
These reports will be coming either here:
https://github.com/timfish/sentry-rust-minidump/blob/fa5ca408c22f2322488bc05c6b63738084b38580/src/lib.rs#L43-L45

Or here:
https://github.com/timfish/sentry-rust-minidump/blob/2ca0dc053e0627609aa0b2da3e8ba67f3b918d03/src/server.rs#L76-L78 

Do you know which process each of these errors came from or have stack traces? In the crash reporter process we tag panics with extra data `event.process` to help identify them:
https://github.com/timfish/sentry-rust-minidump/blob/2ca0dc053e0627609aa0b2da3e8ba67f3b918d03/src/server.rs#L102-L104

App users will not see these errors but I silently logged them to Sentry because I haven't got any apps using this code on thousands of machines and it seemed important to get to the bottom of if and when they occur. We can probably safely ignore them and I'm guessing they're mostly the same cause but different errors per platform.

If you run two instances of your app, or run two instances in close succession, a crash reporting server process will already be running using the unique socket name and the new client should use that reporter because each crash reporting process can support multiple clients. In this case, the 2nd crash reporting process will fail to expose on the uniquely named socket and close.

> I wonder if a timeout is causing that one.

This timeout is used to retry connecting to the crash reporting process. On slower machines it can take a while before it has fully started and is ready for connections.

**Comment by dceddia** [comment]
Sentry doesn't seem to be giving me a stack trace on these, and I don't see an `event.process`. Does that mean this came from my side? This is the JSON from one of the events.

```json
{
  "event_id": "0e151c61c99b427f9add5768e08e631b",
  "project": 6580691,
  "release": "recut@3.2.1",
  "dist": null,
  "platform": "native",
  "message": "",
  "datetime": "2022-08-07T23:30:50.123540Z",
  "tags": [
    [
      "environment",
      "production"
    ],
    [
      "level",
      "error"
    ],
    [
      "os.name",
      "windows"
    ],
    [
      "rust",
      "rustc 1.62.0"
    ],
    [
      "rust.name",
      "rustc"
    ],
    [
      "release",
      "recut@3.2.1"
    ],
    [
      "server_name",
      "DESKTOP"
    ]
  ],
  "_metrics": {
    "bytes.ingested.event": 815,
    "bytes.stored.event": 1625
  },
  "contexts": {
    "device": {
      "arch": "x86_64",
      "type": "device"
    },
    "os": {
      "name": "windows",
      "type": "os"
    },
    "rust": {
      "name": "rustc",
      "version": "1.62.0",
      "channel": "stable",
      "type": "runtime"
    }
  },
  "culprit": "",
  "environment": "production",
  "exception": {
    "values": [
      {
        "type": "StartIpc",
        "value": "No connection could be made because the target machine actively refused it. (os error 10061)"
      }
    ]
  },
  "fingerprint": [
    "{{ default }}"
  ],
  "grouping_config": {
    "enhancements": "eJybzDRxY3J-bm5-npWRgaGlroGxrpHxBABcYgcZ",
    "id": "newstyle:2019-10-29"
  },
  "hashes": [
    "a9ffe8e991ac81daad3f0ac4b6841bae"
  ],
  "ingest_path": [
    {
      "version": "22.7.0",
      "public_key": "..."
    }
  ],
  "key_id": "2396798",
  "level": "error",
  "logger": "",
  "metadata": {
    "display_title_with_tree_label": true,
    "type": "StartIpc",
    "value": "No connection could be made because the target machine actively refused it. (os error 10061)"
  },
  "nodestore_insert": 1659915053.053055,
  "received": 1659915050.926656,
  "sdk": {
    "name": "sentry.rust",
    "version": "0.27.0",
    "integrations": [
      "attach-stacktrace",
      "contexts",
      "panic",
      "process-stacktrace"
    ],
    "packages": [
      {
        "name": "cargo:sentry",
        "version": "0.27.0"
      }
    ]
  },
  "timestamp": 1659915050.12354,
  "title": "StartIpc: No connection could be made because the target machine actively refused it. (os error 10061)",
  "type": "error",
  "version": "7",
  "location": null
}
```

**Comment by timfish** [comment]
Since v0.3.0, `init` returns a `Result` which allows you to handle any errors however you like.

I'm hoping there will be less of these errors since a lot has been improved.

**Comment by dceddia** [comment]
Awesome, thanks! It's been a while since I looked at this, I'll give it another go :)
